### ISSUE TITLE
GoA not listed in OP

### ISSUE THREAD

**Issue by RVestfjord** [uckelman/dw_op#24]
I've noticed that the GoA is not listed for bearers of the Ring awards. They all come with an GoA so it should be listed once one gets admitted to the order.

**Comment by SaraUckelman** [comment]
The ring orders are in the OP database as "goa-bearing awards", just as the Lindquistringes, SG, and Panache are in the OP database as "aoa-bearing awards".  When someone gets one of these, they don't ALSO get a separate entry for a separate AoA.  The only reasons patents are listed separately is because it is possible to get a peerage without a patent, so we need to keep track of which ones came with patents and which ones don't.  You can't get a Ring without a GoA (unless you already have one), same as you can't get a Panache without an AoA (unless you already have one).

(Note that handling GoA orders in this way isn't idiosyncractic, but is how all the other kingdom OPs handle it.)

**Comment by RVestfjord** [comment]
Fair enough.
